# apiVersion: v1
# kind: Service
# metadata:
#   name: guestbook-ui
# spec:
#   ports:
#   - port: 80
#     targetPort: 80
#   selector:
#     app: guestbook-ui

# For my testing, I will change the service from default ClusterIP to NodePort.
apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
    
